#!/usr/bin/env bash
SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
GIT_ROOT="$(cd "${SCRIPT_DIR}" && git rev-parse --show-toplevel)"

export ENVIRONMENT="${ENVIRONMENT:-"talk"}"
export VM_NAME="${VM_NAME:-"${ENVIRONMENT}-dev-docker-host"}"

function finally () {
  rm -f /run/user/$(id -u)/${VM_NAME}-docker.sock
}

trap finally EXIT

tmux new-session -s "${ENVIRONMENT}" -c "$(pwd)/../.." \; \
  set-option -g mouse on \; \
  send-keys "ssh $(whoami)@${VM_NAME}" C-m \; \
  split-window -v \; \
  send-keys "export DOCKER_HOST="unix:///run/user/$(id -u)/${VM_NAME}-docker.sock"" C-m \; \
  select-pane -t 0 \; \
  split-window -h \; \
  send-keys "ssh -N -L "/run/user/$(id -u)/${VM_NAME}-docker.sock:/var/run/docker.sock" $(whoami)@${VM_NAME}" C-m \; \
  split-window -v \; \
  send-keys "ssh -N -L localhost:3000:localhost:3000 -L localhost:9090:localhost:9090 -L localhost:8081:localhost:8081 -L localhost:8181:localhost:8181 -L localhost:8082:localhost:8082 -L localhost:8182:localhost:8182 $(whoami)@${VM_NAME}" C-m \; \
  select-pane -t 3
