version: "3.8"

services:

  ##########################################################
  # Applications                                           #
  ##########################################################

  news-db:
    container_name: news-db
    hostname: news-db
    image: mariadb:11.1.2
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: newsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./news-db/init.sql:/docker-entrypoint-initdb.d/init.sql:z
      - ./datasource/News_Category_Dataset_v3.csv:/etc/News_Category_Dataset_v3.csv:z
    networks:
      - envite

  news:
    container_name: news
    hostname: news
    image: news:1.0.0-SNAPSHOT
    depends_on:
      - news-db
    restart: on-failure
    ports:
      - "8081:8081"
      - "8181:8181"
    environment:
      SERVER_PORT: 8081
      MANAGEMENT_SERVER_PORT: 8181
      SPRING_DATASOURCE_URL: jdbc:mariadb://news-db:3306/newsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - envite

  user-interest-db:
    container_name: user-interest-db
    hostname: user-interest-db
    image: redis:7.2.1-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - envite

  user-interest-db-init:
    container_name: user-interest-db-init
    hostname: user-interest-db-init
    image: user-interest-db-init:1.0.0-SNAPSHOT
    depends_on:
      - user-interest-db
    restart: on-failure
    environment:
      APP_USERSDATASETCSVFILE: /workspace/datasource/users.csv
      APP_NEWSDATASETCSVFILE: /workspace/datasource/News_Category_Dataset_v3.csv
      APP_USERSCOUNT: 10000
      APP_MININTERESTS: 0
      APP_MAXINTERESTS: 10
      APP_NEWSFROMDATE: "2012-01-01"
      APP_NEWSUNTILDATE: "2018-04-30" #"2018-04-30" #"2022-09-23"
      APP_RANDOMSEED: 11235813
      SPRING_DATA_REDIS_HOST: user-interest-db
      SPRING_DATA_REDIS_PORT: 6379
    volumes:
      - ./datasource/users.csv:/workspace/datasource/users.csv:z
      - ./datasource/News_Category_Dataset_v3.csv:/workspace/datasource/News_Category_Dataset_v3.csv:z
    networks:
      - envite

  interest-feed:
    container_name: interest-feed
    hostname: interest-feed
    image: interest-feed:1.0.0-SNAPSHOT
    depends_on:
      - user-interest-db
    restart: on-failure
    ports:
      - "8082:8082"
      - "8182:8182"
    environment:
      SERVER_PORT: 8082
      MANAGEMENT_SERVER_PORT: 8182
      SPRING_DATA_REDIS_HOST: user-interest-db
      SPRING_DATA_REDIS_PORT: 6379
      SERVICE_NEWS_URL: http://news:8081
      FEED_LIMIT: 20
      FEED_PERIOD: P1W
    networks:
      - envite

#  benchmark:
#    container_name: benchmark
#    hostname: benchmark
#    image: benchmark:1.0.0-SNAPSHOT
#    restart: on-failure
#    ports:
#      - "8183:8183"
#    environment:
#      SERVER_PORT: 8183
#      MANAGEMENT_SERVER_PORT: 8183
#      SERVICE_INTERESTFEED_URL: http://interest-feed:8082
#      BENCHMARK_INITIALDELAY: '30s'
#      BENCHMARK_INTERMEDIATEDELAY: '30s'
#      BENCHMARK_SHUTDOWNDELAY: '30s'
#      BENCHMARK_NUMBEROFUSERS: 100
#      BENCHMARK_DATE: '2013-08-05'
#      BENCHMARK_REQUESTDELAY: '1s'
#      BENCHMARK_TESTDURATION: '0s'
#      BENCHMARK_REQUESTSPERUSER: 250
#    networks:
#      - envite

  ##########################################################
  # Monitoring                                             #
  ##########################################################

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.47.0
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/config.yaml:/etc/prometheus/prometheus.yml:roz
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - envite

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:10.1.2
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning:roz
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    networks:
      - envite

  cadvisor:
    container_name: cadvisor
    hostname: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    restart: on-failure
    ports:
      - "9400:8080"
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
    devices:
      - /dev/kmsg
    command:
      - "--store_container_labels=false"
      - "--docker_only=true"
    networks:
      - envite

  node_exporter:
    container_name: node_exporter
    hostname: node_exporter
    image: quay.io/prometheus/node-exporter:v1.6.1
    restart: on-failure
    network_mode: host
    pid: host
    volumes:
      - /:/rootfs:ro,rslave
    command:
      - '--path.rootfs=/rootfs'

  redis-prometheus-exporter:
    container_name: redis-prometheus-exporter
    hostname: redis-prometheus-exporter
    image: oliver006/redis_exporter:v1.54.0-alpine
    restart: on-failure
    ports:
      - "9121:9121"
    command:
      - '--redis.addr='
    networks:
      - envite

  mariadb-prometheus-exporter:
    container_name: mariadb-prometheus-exporter
    hostname: mariadb-prometheus-exporter
    image: prom/mysqld-exporter:v0.15.0
    restart: on-failure
    ports:
      - "9104:9104"
    environment:
      MYSQLD_EXPORTER_PASSWORD: password
    command:
      - '--mysqld.username=user'
    networks:
      - envite

networks:
  envite:
    driver: bridge