version: "3.8"

services:

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.48.0
    restart: always
    networks:
      - envite
    ports:
      - "9090:9090"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./monitoring/prometheus/config.yaml:/etc/prometheus/prometheus.yaml:roz
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=365d"
    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.middlewares: "auth-user@file"

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:10.2.0
    restart: always
    networks:
      - envite
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning:roz
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.middlewares: "auth-user@file"

  node_exporter:
    container_name: node_exporter
    hostname: node_exporter
    image: quay.io/prometheus/node-exporter:v1.6.1
    restart: always
    network_mode: host
    pid: host
    user: root
    privileged: true
    volumes:
      - /:/rootfs:ro,rslave
    command:
      - "--path.rootfs=/rootfs"

  cadvisor:
    container_name: cadvisor
    hostname: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    restart: always
    networks:
      - envite
    ports:
      - "9338:8080"
    privileged: true
    volumes:
      - /:/rootfs:ro,rslave
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
    devices:
      - /dev/kmsg
    command:
      - "--store_container_labels=false"
      - "--docker_only=true"

  scaphandre:
    container_name: scaphandre
    hostname: scaphandre
    image: hubblo/scaphandre:0.5.0
    restart: always
    networks:
      - envite
    ports:
      - "9500:8080"
    privileged: true
    volumes:
      - /proc:/proc
      - /sys:/sys
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "prometheus"
      - "--containers"

  redis-prometheus-exporter:
    container_name: redis-prometheus-exporter
    hostname: redis-prometheus-exporter
    image: oliver006/redis_exporter:v1.55.0-alpine
    restart: always
    networks:
      - envite
    ports:
      - "9121:9121"
    command:
      - '--redis.addr='

  mariadb-prometheus-exporter:
    container_name: mariadb-prometheus-exporter
    hostname: mariadb-prometheus-exporter
    image: prom/mysqld-exporter:v0.15.0
    restart: always
    networks:
      - envite
    ports:
      - "9104:9104"
    environment:
      MYSQLD_EXPORTER_PASSWORD: password
    command:
      - '--mysqld.username=user'

volumes:
  prometheus-data:
    name: prometheus-data

networks:
  envite:
    name: envite
    external: true