version: "3.8"

services:

  #news:
  #  container_name: news
  #  hostname: news
  #  image: enviteconsulting/news
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  ports:
  #    - "8081:8081"
  #  networks:
  #    - envite

  news-db:
    container_name: news-db
    hostname: news-db
    image: mariadb:11.1.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    networks:
      - envite

  #interest-feed:
  #  container_name: interest-feed
  #  hostname: interest-feed
  #  image: enviteconsulting/interest-feed
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  ports:
  #    - "8082:8082"
  #  networks:
  #    - envite

  interest-feed-db:
    container_name: interest-feed-db
    hostname: interest-feed-db
    image: redis:7.2.1-alpine
    ports:
      - "6379:6379"
    networks:
      - envite

volumes:
  data:

networks:
  envite:
    driver: bridge