version: "3.8"

services:

  news-cache:
    container_name: news-cache
    hostname: news-cache
    image: news:1.0.0
    restart: always
    networks:
      - envite
    ports:
      - "9081:9081"
      - "9181:9181"
    environment:
      SERVER_PORT: 9081
      MANAGEMENT_SERVER_PORT: 9181
      SPRING_DATASOURCE_URL: jdbc:mariadb://news-db:3306/newsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  interest-feed-cache:
    container_name: interest-feed-cache
    hostname: interest-feed-cache
    image: interest-feed:1.0.0
    restart: always
    networks:
      - envite
    ports:
      - "9082:9082"
      - "9182:9182"
    environment:
      SERVER_PORT: 9082
      MANAGEMENT_SERVER_PORT: 9182
      SPRING_DATA_REDIS_HOST: user-interest-db
      SPRING_DATA_REDIS_PORT: 6379
      SERVICE_NEWS_URL: http://news-cache:9081
      FEED_LIMIT: 20
      FEED_PERIOD: P1W
      OKHTTP_CLIENT_CACHE_ENABLED: "true"
      OKHTTP_CLIENT_CACHE_DIRECTORY: "/home/cnb/.cache/http_cache"
      OKHTTP_CLIENT_CACHE_MAXSIZE: 25MB

networks:
  envite:
    name: envite
    external: true