version: "3.8"

services:

  benchmark-default:
    container_name: benchmark-default
    hostname: benchmark-default
    image: benchmark:1.0.0
    restart: on-failure
    ports:
      - "8183:8183"
    environment:
      SERVER_PORT: 8183
      MANAGEMENT_SERVER_PORT: 8183
      SERVICE_INTERESTFEED_URL: http://interest-feed-default:8082
      BENCHMARK_INITIALDELAY: '0s'
      BENCHMARK_INTERMEDIATEDELAY: '30s'
      BENCHMARK_SHUTDOWNDELAY: '15s'
      BENCHMARK_NUMBEROFUSERS: 100
      BENCHMARK_DATE: '2013-08-05'
      BENCHMARK_REQUESTDELAY: '1s'
      BENCHMARK_TESTDURATION: '0s'
      BENCHMARK_REQUESTSPERUSER: 250
    networks:
      - envite

networks:
  envite:
    name: envite
    external: true