= Pattern: Predictive Caching

== Quick Start

Download required data sources from link:https://www.kaggle.com[Kaggle] into the link:datasource/[] directory
and prepare the datasets for their usage.
The required steps are described in the link:datasource/README.adoc[Datasources Readme] file.

.Build container images:
[source,bash]
----
./gradlew bootBuildImage
----

.Provide read permissions to those files to anyone to allow access within container:
[source,bash]
----
chmod -R g+r,o+r datasource/
chmod -R g+r,o+r news-db/
chmod -R g+r,o+r monitoring/
----

.Run demo environment:
[source,bash]
----
docker-compose up -d
----

.Wait until the user-interest-db-init has been completed:
[source,bash]
----
docker ps -a --format 'table {{.Names}}\t{{.Status}}'
----
----
NAMES                  STATUS
news-db                Up 5 minutes
user-interest-db       Up 5 minutes
news                   Up 5 minutes
user-interest-db-init  Exited (0) 5 minutes ago
interest-feed          Up 5 minutes
----

== News Service

.Test curl request to get recommended news:
[source,bash]
----
curl -XPOST -H "Content-type: application/json" -d '{"topics" : ["U.S. NEWS"], "fromDate":"2012-02-03", "untilDate":"2022-02-10", "limit":10}' 'http://localhost:8081/recommendedNews'
----

.Test curl request to get latest news:
[source,bash]
----
curl -XGET 'http://localhost:8081/latestNews?untilDate=2022-02-10&limit=3'
----

== Interest Feed Service

.Test curl request to get feed for a user:
[source,bash]
----
curl -XGET -H "Content-type: application/json" 'http://localhost:8082/feed/mariameyer000?date=2013-08-05'
----

.Test curl request to get usernames:
[source,bash]
----
curl -XGET -H "Content-type: application/json" 'http://localhost:8082/usernames?limit=10'
----

.Test curl request to get interests:
[source,bash]
----
curl -XGET -H "Content-type: application/json" 'http://localhost:8082/interests?limit=10'
----

.Test curl request to get interests by user:
[source,bash]
----
curl -XGET -H "Content-type: application/json" 'http://localhost:8082/interests/mariameyer000'
----

== ToDos

* [x] Feed should always contain news (use latest feeds API)
* [x] API to show all users (and maybe their interests)
* [ ] Benchmark app (Uwe)
* [x] Monitoring setup and metrics for CPU time, CPU usage and memory of services and dbs
* [x] Metrics for service and db internals like http connections, ...
* [ ] UI for Feeds and Usernames (Micha)
* [ ] Implementation of simple Feed caching (enable via config) (Uwe)
* [ ] Monitoring for Watt and CO2e (Micha)
* [ ] Implementation of predictive caching
* [ ] Setup for Kubernetes
* [ ] Documentation with images