= Pattern: Predictive Caching

== Quick Start

.Build container images
[source,bash]
----
./gradlew bootBuildImage
----

.Provide read permissions to those files to anyone to allow access within container
[source,bash]
----
chmod -R g+r,o+r datasource/
chmod -R g+r,o+r news-db/
----

.Run demo environment
[source,bash]
----
docker-compose up -d
----

== News Service

.Test curl request to get recommended news:
[source,bash]
----
curl -XPOST -H "Content-type: application/json" -d '{"topics" : ["U.S. NEWS"], "limit":10, "fromDate":"2012-02-03", "untilDate":"2022-02-10"}' 'http://localhost:8081/recommendedNews'
----

.Test curl request to get latest news:
[source,bash]
----
curl -XGET 'http://localhost:8081/latestNews?limit=3&untilDate=2022-02-10'
----

== Interest Feed Service

.Test curl request to get feed for a user:
[source,bash]
----
curl -XGET -H "Content-type: application/json" 'http://localhost:8082/feed/supposed2bworking?date=2022-02-10'
----

== ToDos

* [] Feed should always contain news (use latest feeds API)
* [] API to show all users (and maybe their interests)
* [] Benchmark app
* [] Monitoring setup and metrics for CPU time, CPU usage and memory of services and dbs
* [] Metrics for service internals like http connections, ...

* [] Implementation of simple Feed caching (enable via config)
* [] Monitoring for Watt and CO2e
* [] Implementation of predictive caching
* [] Migrate to Kubernetes