{
 "title": "Application (Technical)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(process_uptime_seconds,job)"
    }
   },
   {
    "name": "http_server_uri",
    "label": "http_server_uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_bucket{service=~\"$service\"},uri)"
    }
   },
   {
    "name": "http_client_uri",
    "label": "http_client_uri",
    "query": {
     "query": "label_values(http_client_requests_seconds_bucket{service=~\"$service\"},uri)"
    }
   },
   {
    "name": "method",
    "label": "method",
    "query": {
     "query": "label_values(method_timed_seconds_bucket{service=~\"$service\"},method)"
    }
   },
   {
    "name": "redis_remote",
    "label": "redis_remote",
    "query": {
     "query": "label_values(lettuce_command_completion_seconds_bucket{service=~\"$service\"},remote)"
    }
   },
   {
    "name": "redis_command",
    "label": "redis_command",
    "query": {
     "query": "label_values(lettuce_command_completion_seconds_bucket{service=~\"$service\", remote=\"$redis_remote\"},command)"
    }
   },
   {
    "name": "hikari_pool",
    "label": "hikari_pool",
    "query": {
     "query": "label_values(hikaricp_connections_acquire_seconds_bucket{service=~\"$service\"},pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Http Server Connections (Tomcat)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Tomcat: Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tomcat_threads_current_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}: current"
      },
      {
       "expr": "tomcat_threads_busy_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}: busy"
      }
     ]
    },
    {
     "title": "Tomcat: Threads Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tomcat_threads_config_max_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Tomcat: Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tomcat_connections_current_connections{service=~\"$service\"}",
       "legendFormat": "{{service}}: total"
      },
      {
       "expr": "tomcat_connections_keepalive_current_connections{service=~\"$service\"}",
       "legendFormat": "{{service}}: keepAlive"
      }
     ]
    },
    {
     "title": "Tomcat: Max Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tomcat_connections_config_max_connections{service=~\"$service\"}",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http Server Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server Connections: Completed Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}})"
      }
     ]
    },
    {
     "title": "Server Connections: Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}}) (rate)"
      },
      {
       "expr": "http_server_requests_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}}) (max per request)"
      },
      {
       "expr": "irate(http_server_requests_seconds_sum{service=~\"$service\"}[15s]) / irate(http_server_requests_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}}) (avg per request)"
      }
     ]
    }
   ]
  },
  {
   "title": "Http Server Latency Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server Request Latency: $http_server_uri (SUCCESS)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "repeat": "http_server_uri",
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_server_uri\",outcome=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Server Request Latency: $http_server_uri (ERROR)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "repeat": "http_server_uri",
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_server_uri\",outcome!=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http Client Connections (OkHttp)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "OkHttp Client Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "okhttp_pool_connection_count_connections{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http Client Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Client Requests: Completed Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(http_client_requests_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}})"
      }
     ]
    },
    {
     "title": "Client Requests: Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_client_requests_seconds_sum{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}}) (rate)"
      },
      {
       "expr": "http_client_requests_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}}) (max per request)"
      },
      {
       "expr": "irate(http_client_requests_seconds_sum{service=~\"$service\"}[15s]) / irate(http_client_requests_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}}) (avg per request)"
      }
     ]
    }
   ]
  },
  {
   "title": "Http Client Latency Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Client Request Latency: $http_client_uri (SUCCESS)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "repeat": "http_client_uri",
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_client_uri\",outcome=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Client Request Latency: $http_client_uri (ERROR)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "repeat": "http_client_uri",
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_client_uri\",outcome!=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ExecutorService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Executor: Queued Tasks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "executor_queued_tasks{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Queue Remaining Tasks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "executor_queue_remaining_tasks{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Completed Tasks Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(executor_completed_tasks_total{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Pool Size Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "executor_pool_size_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Pool Core Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "executor_pool_core_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Pool Max Threads",
     "type": "timeseries",
     "description": "Additional threads are only added if queue has no remaining elements.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "executor_pool_max_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Task Idle Duration Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(executor_idle_seconds_sum{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{ name }} (total)"
      },
      {
       "expr": "irate(executor_idle_seconds_sum{service=~\"$service\"}[15s])/(executor_queued_tasks{service=~\"$service\"}>0)",
       "legendFormat": "{{service}}: {{ name }} (avg per task)"
      }
     ]
    },
    {
     "title": "Executor: Task Idle Seconds/Task",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "executor_idle_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{ name }} (max)"
      },
      {
       "expr": "executor_idle_seconds_sum{service=~\"$service\"} / executor_idle_seconds_count{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{ name }} (avg since start of app)"
      }
     ]
    },
    {
     "title": "Executor: Task Active Duration Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(executor_seconds_sum{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (total)"
      },
      {
       "expr": "irate(executor_seconds_sum{service=~\"$service\"}[15s])/(executor_pool_size_threads{service=~\"$service\"}>0)",
       "legendFormat": "{{service}}: {{ name }} (avg per task)"
      }
     ]
    },
    {
     "title": "Executor: Task Active Seconds/Task",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "executor_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{ name }} (max)"
      },
      {
       "expr": "executor_seconds_sum{service=~\"$service\"} / executor_seconds_count{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{ name }} (avg since start of app)"
      }
     ]
    }
   ]
  },
  {
   "title": "Method Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Method Calls: Completed Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(method_timed_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{class}} {{method}} ({{exception}})"
      }
     ]
    },
    {
     "title": "Method Calls: Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(method_timed_seconds_sum{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{class}} {{method}} ({{exception}}) (rate)"
      },
      {
       "expr": "method_timed_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{class}} {{method}} ({{exception}}) (max per request)"
      },
      {
       "expr": "irate(method_timed_seconds_sum{service=~\"$service\"}[15s]) / irate(method_timed_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{class}} {{method}} ({{exception}}) (avg per request)"
      }
     ]
    }
   ]
  },
  {
   "title": "Method Latency Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Method Latency: $method (success)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "repeat": "method",
     "targets": [
      {
       "expr": "sum(increase(method_timed_seconds_bucket{service=~\"$service\",method=~\"$method\",exception=\"none\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Method Latency: $method (error)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "repeat": "method",
     "targets": [
      {
       "expr": "sum(increase(method_timed_seconds_bucket{service=~\"$service\",method=~\"$method\",exception!=\"none\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Client Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Requests: Completed Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(lettuce_command_completion_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{remote}} {{command}}"
      }
     ]
    },
    {
     "title": "Redis Requests: Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(lettuce_command_completion_seconds_sum{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{remote}} {{command}} (rate)"
      },
      {
       "expr": "lettuce_command_completion_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{remote}} {{command}} (max per request)"
      },
      {
       "expr": "irate(lettuce_command_completion_seconds_sum{service=~\"$service\"}[15s]) / irate(lettuce_command_completion_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{remote}} {{command}} (avg per request)"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis Client Latency Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Client Request Latency: $redis_remote $redis_command",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "repeat": "redis_command",
     "targets": [
      {
       "expr": "sum(increase(lettuce_command_completion_seconds_bucket{service=~\"$service\",remote=\"$redis_remote\",command=~\"$redis_command\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JDBC Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Min",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jdbc_connections_min{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{name}}"
      }
     ]
    },
    {
     "title": "Active",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jdbc_connections_active{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{name}}"
      }
     ]
    },
    {
     "title": "Max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jdbc_connections_max{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hikari Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{pool}} active connections"
      },
      {
       "expr": "hikaricp_connections_idle{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{pool}} idle connections"
      },
      {
       "expr": "hikaricp_connections_pending{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{pool}} pending threads"
      }
     ]
    },
    {
     "title": "Min",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "hikaricp_connections_min{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{pool}}"
      }
     ]
    },
    {
     "title": "Max",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "hikaricp_connections_max{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{pool}}"
      }
     ]
    },
    {
     "title": "Connections Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(hikaricp_connections_usage_seconds_sum{service=~\"$service\"}[15s]) / irate(hikaricp_connections_usage_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{pool}} usage time"
      },
      {
       "expr": "irate(hikaricp_connections_creation_seconds_sum{service=~\"$service\"}[15s]) / irate(hikaricp_connections_creation_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{pool}} creation time"
      },
      {
       "expr": "irate(hikaricp_connections_acquire_seconds_sum{service=~\"$service\"}[15s]) / irate(hikaricp_connections_acquire_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{service}}: {{pool}} acquire time"
      }
     ]
    },
    {
     "title": "Total Timeout",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{service=~\"$service\"}",
       "legendFormat": "{{service}}: {{pool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hikari Connections Latency Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hikari Creation Latency: $service $hikari_pool",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
     "repeat": "hikari_pool",
     "targets": [
      {
       "expr": "sum(increase(hikaricp_connections_creation_seconds_bucket{service=~\"$service\",pool=\"$hikari_pool\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Hikari Acquire Latency: $service $hikari_pool",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
     "repeat": "hikari_pool",
     "targets": [
      {
       "expr": "sum(increase(hikaricp_connections_acquire_seconds_bucket{service=~\"$service\",pool=\"$hikari_pool\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Hikari Usage Latency: $service $hikari_pool",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
     "repeat": "hikari_pool",
     "targets": [
      {
       "expr": "sum(increase(hikaricp_connections_usage_seconds_bucket{service=~\"$service\",pool=\"$hikari_pool\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}