{
 "title": "Benchmark Evaluation",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "variant", "label": "variant", "query": { "query": "label_values(up,variant)" } }
  ]
 },
 "panels": [
  { "title": "Overview Benchmark (Feed)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Simulations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(benchmark_user_simulations_current{service=~\"benchmark-${variant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Simulations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum(benchmark_user_simulations_current{service=~\"benchmark-${variant}\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Benchmark Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(benchmark_duration_seconds_total{service=~\"benchmark-${variant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Simulations Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(benchmark_user_simulations_duration_seconds_total{service=~\"benchmark-${variant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feed Recommended News 50p",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(feed_recommended_news_size_bucket{service=~\"interest-feed-${variant}\"}[$__interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feed Recommended News 25p",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(feed_recommended_news_size_bucket{service=~\"interest-feed-${variant}\"}[$__interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(http_client_requests_seconds_count{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by (outcome) (\n    http_client_requests_seconds_count{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\"} \n    or clamp_max(absent(http_client_requests_seconds_count{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\",outcome=\"SUCCESS\"}),0) \n    or clamp_max(absent(http_client_requests_seconds_count{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\",outcome=\"UNKNOWN\"}),0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(http_client_requests_seconds_sum{service=~\"benchmark-${variant}\", uri=\"/feed/{username}?date={date}\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by (outcome) (\n    http_client_requests_seconds_sum{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\"} \n    or clamp_max(absent(http_client_requests_seconds_sum{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\",outcome=\"SUCCESS\"}),0) \n    or clamp_max(absent(http_client_requests_seconds_sum{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\",outcome=\"UNKNOWN\"}),0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_client_requests_seconds_count{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\"}[15s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "sum by (outcome) (irate(http_client_requests_seconds_count{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\"}[15s]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Request Latency 95p",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_requests_seconds_bucket{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\"}[$__interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency 50p",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_client_requests_seconds_bucket{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\"}[$__interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_bucket{service=~\"benchmark-${variant}\",uri=\"/feed/{username}?date={date}\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (outcome) (irate(http_client_requests_seconds_sum{service=~\"benchmark-${variant}\", uri=\"/feed/{username}?date={date}\"}[15s]) / irate(http_client_requests_seconds_count{service=~\"benchmark-${variant}\", uri=\"/feed/{username}?date={date}\"}[15s]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  { "title": "Energy and Power Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Energy consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(sum(scaph_process_power_consumption_microwatts{container_names=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"})by(container_names)[$__range:1s]) / 1000000 / 3600)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy consumption",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,sum_over_time(sum(scaph_process_power_consumption_microwatts{container_names=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"})by(container_names)[$__range:1s]) / 1000000 / 3600)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{container_names=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"})by(container_names)/1000000",
     "legendFormat": "{{container_names}}"
    }
   ]
  },
  { "title": "Overview Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Time Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by (name) (container_cpu_usage_seconds_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"}[15s])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_rss{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"}[15s])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\"}[15s])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Read Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(container_blkio_device_usage_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\",operation=\"Read\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by (name) (container_blkio_device_usage_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\",operation=\"Read\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (irate(container_blkio_device_usage_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\",operation=\"Read\"}[15s]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Write Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(container_blkio_device_usage_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\",operation=\"Write\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by (name) (container_blkio_device_usage_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\",operation=\"Write\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (irate(container_blkio_device_usage_total{name=~\"news-${variant}|news-db|interest-feed-${variant}|user-interest-db|benchmark-${variant}\",operation=\"Write\"}[15s]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Overview Interest Feed (Recommended News)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (\n    http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\"} \n    or clamp_max(absent(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\",outcome=\"SUCCESS\"}),0) \n    or clamp_max(absent(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\",outcome=\"UNKNOWN\"}),0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 6, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum(http_client_requests_seconds_sum{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 9, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (\n    http_client_requests_seconds_sum{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\"} \n    or clamp_max(absent(http_client_requests_seconds_sum{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\",outcome=\"SUCCESS\"}),0) \n    or clamp_max(absent(http_client_requests_seconds_sum{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\",outcome=\"UNKNOWN\"}),0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\"}[15s]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 43 },
     "targets": [
      {
       "expr": "sum by (outcome) (irate(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\"}[15s]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "title": "Request Latency 95p",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_client_requests_seconds_bucket{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Latency 50p",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_client_requests_seconds_bucket{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 51 },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_bucket{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Request Latency (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (outcome) (irate(http_client_requests_seconds_sum{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\"}[15s]) / irate(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/recommended?topics={topics}&fromDate={fromDate}&untilDate={untilDate}&limit={limit}\"}[15s]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview Interest Feed (Latest News)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (\n    http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\"} \n    or clamp_max(absent(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\",outcome=\"SUCCESS\"}),0) \n    or clamp_max(absent(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\",outcome=\"UNKNOWN\"}),0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 6, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum(http_client_requests_seconds_sum{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 9, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum by (outcome) (\n    http_client_requests_seconds_sum{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\"} \n    or clamp_max(absent(http_client_requests_seconds_sum{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\",outcome=\"SUCCESS\"}),0) \n    or clamp_max(absent(http_client_requests_seconds_sum{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\",outcome=\"UNKNOWN\"}),0)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\"}[15s]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 44 },
     "targets": [
      {
       "expr": "sum by (outcome) (irate(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\"}[15s]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    },
    {
     "title": "Request Latency 95p",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_client_requests_seconds_bucket{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Latency 50p",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_client_requests_seconds_bucket{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\"}[$__interval])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 52 },
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_bucket{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Request Latency (Avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (outcome) (irate(http_client_requests_seconds_sum{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\"}[15s]) / irate(http_client_requests_seconds_count{service=~\"interest-feed-${variant}\",uri=\"/news/latest?untilDate={untilDate}&limit={limit}\"}[15s]))",
       "legendFormat": "{{outcome}}"
      }
     ]
    }
   ]
  }
 ]
}