{
 "title": "Benchmark",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Simulations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Simulations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance) (benchmark_user_simulations_current{service=\"benchmark\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Feed Recommended News Size (Distribution)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(feed_recommended_news_size_bucket{service=\"interest-feed\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Request Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance) (http_client_requests_seconds_count{service=\"benchmark\",uri=\"/feed/{username}?date={date}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Count (By State)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance,outcome,status,exception) (http_client_requests_seconds_count{service=\"benchmark\",uri=\"/feed/{username}?date={date}\"})",
     "legendFormat": "{{instance}}: {{outcome}} ({{state}}) ({{exception}})"
    }
   ]
  },
  {
   "title": "Request Count Per User Simulation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (instance) (http_client_requests_seconds_count{service=\"benchmark\",uri=\"/feed/{username}?date={date}\"}) / sum by (instance) (benchmark_user_simulations_current{service=\"benchmark\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Count Per User Simulation (By State)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (instance,outcome,status,exception) (http_client_requests_seconds_count{service=\"benchmark\",uri=\"/feed/{username}?date={date}\"}) / on (instance) group_left() (sum by (instance) (benchmark_user_simulations_current{service=\"benchmark\"}))",
     "legendFormat": "{{instance}}: {{outcome}} ({{status}}) ({{exception}})"
    }
   ]
  },
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (instance) (irate(http_client_requests_seconds_count{service=\"benchmark\",uri=\"/feed/{username}?date={date}\"}[15s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (By State)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (instance, outcome, status, exception) (irate(http_client_requests_seconds_count{service=\"benchmark\",uri=\"/feed/{username}?date={date}\"}[15s]))",
     "legendFormat": "{{instance}}: {{outcome}} ({{status}}) ({{exception}})"
    }
   ]
  },
  {
   "title": "Request Rate Per User Simulation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (instance) (irate(http_client_requests_seconds_count{service=\"benchmark\",uri=\"/feed/{username}?date={date}\"}[15s])) / sum by (instance) (benchmark_user_simulations_current{service=\"benchmark\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate Per User Simulation (By State)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (instance, outcome, status, exception) (irate(http_client_requests_seconds_count{service=\"benchmark\",uri=\"/feed/{username}?date={date}\"}[15s])) / on (instance) group_left() (sum by (instance) (benchmark_user_simulations_current{service=\"benchmark\"}))",
     "legendFormat": "{{instance}}: {{outcome}} ({{status}}) ({{exception}})"
    }
   ]
  },
  { "title": "Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (instance) (irate(http_client_requests_seconds_sum{service=\"benchmark\", uri=\"/feed/{username}?date={date}\"}[15s]) / irate(http_client_requests_seconds_count{service=\"benchmark\", uri=\"/feed/{username}?date={date}\"}[15s]))",
     "legendFormat": "{{instance}}: Average"
    },
    {
     "expr": "max by (instance) (http_client_requests_seconds_max{service=\"benchmark\", uri=\"/feed/{username}?date={date}\"})",
     "legendFormat": "{{instance}}: Max"
    }
   ]
  },
  {
   "title": "Request Duration (By State)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (instance,outcome,status,exception) (irate(http_client_requests_seconds_sum{service=\"benchmark\", uri=\"/feed/{username}?date={date}\"}[15s]) / irate(http_client_requests_seconds_count{service=\"benchmark\", uri=\"/feed/{username}?date={date}\"}[15s]))",
     "legendFormat": "{{instance}}: {{outcome}} ({{status}}) ({{exception}}) Average"
    },
    {
     "expr": "max by (instance,outcome,status,exception) (http_client_requests_seconds_max{service=\"benchmark\", uri=\"/feed/{username}?date={date}\"})",
     "legendFormat": "{{instance}}: {{outcome}} ({{status}}) ({{exception}}) Max"
    }
   ]
  },
  {
   "title": "Request Duration Histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_bucket{service=\"benchmark\",uri=\"/feed/{username}?date={date}\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Request Duration Histogram (SUCCESS)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_bucket{service=\"benchmark\",uri=\"/feed/{username}?date={date}\",outcome=\"SUCCESS\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Request Duration Histogram (ERROR)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum(increase(http_client_requests_seconds_bucket{service=\"benchmark\",uri=\"/feed/{username}?date={date}\",outcome!=\"SUCCESS\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}