{
 "title": "HTTP Connections",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(process_uptime_seconds,job)"
    }
   },
   {
    "name": "http_server_uri",
    "label": "http_server_uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_bucket{service=~\"$service\"},uri)"
    }
   },
   {
    "name": "http_client_uri",
    "label": "http_client_uri",
    "query": {
     "query": "label_values(http_client_requests_seconds_bucket{service=~\"$service\"},uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server Connections (Tomcat)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tomcat: Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{service=~\"$service\"}",
     "legendFormat": "{{service}} (current)"
    },
    {
     "expr": "tomcat_threads_busy_threads{service=~\"$service\"}",
     "legendFormat": "{{service}} (busy)"
    }
   ]
  },
  {
   "title": "Tomcat: Threads Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threads_config_max_threads{service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Tomcat: Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_connections_current_connections{service=~\"$service\"}",
     "legendFormat": "{{service}} (total)"
    },
    {
     "expr": "tomcat_connections_keepalive_current_connections{service=~\"$service\"}",
     "legendFormat": "{{service}} (keepAlive)"
    }
   ]
  },
  {
   "title": "Tomcat: Max Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_connections_config_max_connections{service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Tomcat: Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions{service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Tomcat: Sessions Expiration Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(tomcat_sessions_expired_sessions_total{service=~\"$service\"}[15s])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Tomcat: Max Alive Session Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tomcat_sessions_alive_max_seconds{service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Connections: Completed Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{service=~\"$service\"}[15s])",
     "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}})"
    }
   ]
  },
  {
   "title": "Server Connections: Request Duration Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{service=~\"$service\"}[15s])",
     "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}}) (total)"
    },
    {
     "expr": "irate(http_server_requests_seconds_sum{service=~\"$service\"}[15s]) / irate(http_server_requests_seconds_count{service=~\"$service\"}[15s])",
     "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}}) (avg per request)"
    }
   ]
  },
  {
   "title": "Server Connections: Duration/Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{service=~\"$service\"}",
     "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}}) (max)"
    },
    {
     "expr": "http_server_requests_seconds_sum{service=~\"$service\"} / http_server_requests_seconds_count{service=~\"$service\"}",
     "legendFormat": "{{service}}: {{method}} {{uri}} ({{status}}) (avg since start of app)"
    }
   ]
  },
  {
   "title": "Server Latency Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server Request Latency: $http_server_uri (SUCCESS)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "repeat": "http_server_uri",
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_server_uri\",outcome=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Server Request Latency: $http_server_uri (ERROR)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "repeat": "http_server_uri",
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_server_uri\",outcome!=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "TaskExecutor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Executor: Queued Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_queued_tasks{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Queue Remaining Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_queue_remaining_tasks{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Completed Tasks Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(executor_completed_tasks_total{service=~\"$service\"}[1m])",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Pool Size Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_pool_size_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Pool Core Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_pool_core_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Pool Max Threads",
     "type": "graph",
     "description": "Additional threads are only added if queue has no remaining elements.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_pool_max_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Task Idle Duration Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(executor_idle_seconds_sum{service=~\"$service\"}[1m])",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (total)"
      },
      {
       "expr": "irate(executor_idle_seconds_sum{service=~\"$service\"}[1m])/(executor_queued_tasks{service=~\"$service\"}>0)",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (avg per task)"
      }
     ]
    },
    {
     "title": "Executor: Task Idle Seconds/Task",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "executor_idle_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (max)"
      },
      {
       "expr": "executor_idle_seconds_sum{service=~\"$service\"} / executor_idle_seconds_count{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (avg since start of app)"
      }
     ]
    },
    {
     "title": "Executor: Task Active Duration Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(executor_seconds_sum{service=~\"$service\"}[1m])",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (total)"
      },
      {
       "expr": "irate(executor_seconds_sum{service=~\"$service\"}[1m])/(executor_pool_size_threads{service=~\"$service\"}>0)",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (avg per task)"
      }
     ]
    },
    {
     "title": "Executor: Task Active Seconds/Task",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "executor_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (max)"
      },
      {
       "expr": "executor_seconds_sum{service=~\"$service\"} / executor_seconds_count{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (avg since start of app)"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Connections (Apache)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Apache Client Connections",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "httpcomponents_httpclient_pool_total_max{service=~\"$service\"}",
       "legendFormat": "Max Total"
      },
      {
       "expr": "httpcomponents_httpclient_pool_route_max_default{service=~\"$service\"}",
       "legendFormat": "Max Per Route"
      },
      {
       "expr": "httpcomponents_httpclient_pool_total_connections{service=~\"$service\",state=\"leased\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "httpcomponents_httpclient_pool_total_connections{service=~\"$service\",state=\"available\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "httpcomponents_httpclient_pool_total_pending{service=~\"$service\"}",
       "legendFormat": "Pending"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Connections (Netty)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Netty Client Connections",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "reactor_netty_connection_provider_total_connections{service=~\"$service\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "reactor_netty_connection_provider_active_connections{service=~\"$service\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "reactor_netty_connection_provider_idle_connections{service=~\"$service\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "reactor_netty_connection_provider_pending_connections{service=~\"$service\"}",
       "legendFormat": "Pending"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Client Requests: Completed Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(http_client_requests_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{method}} {{uri}} ({{status}})"
      }
     ]
    },
    {
     "title": "Client Requests: Request Duration Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_client_requests_seconds_sum{service=~\"$service\"}[15s])",
       "legendFormat": "{{method}} {{uri}} ({{status}}) (total)"
      },
      {
       "expr": "irate(http_client_requests_seconds_sum{service=~\"$service\"}[15s]) / irate(http_client_requests_seconds_count{service=~\"$service\"}[15s])",
       "legendFormat": "{{method}} {{uri}} ({{status}}) (avg per request)"
      }
     ]
    },
    {
     "title": "Client Requests: Duration/Request",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_client_requests_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{method}} {{uri}} ({{status}}) (max)"
      },
      {
       "expr": "http_client_requests_seconds_sum{service=~\"$service\"} / http_client_requests_seconds_count{service=~\"$service\"}",
       "legendFormat": "{{method}} {{uri}} ({{status}}) (avg since start of app)"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Latency Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Client Request Latency: $http_client_uri (SUCCESS)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "repeat": "http_client_uri",
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_client_uri\",outcome=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Client Request Latency: $http_client_uri (ERROR)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "repeat": "http_client_uri",
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_client_uri\",outcome!=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}