{
 "title": "Scaphandre",
 "tags": [
  "scaphandre",
  "energy",
  "power"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Host metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Host energy consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "scaph_host_energy_microjoules/3600000000",
     "legendFormat": "Socket {{socket_id}}"
    }
   ]
  },
  {
   "title": "Host power consumption (Mean)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scaph_host_power_microwatts/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host power consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_host_power_microwatts/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Socket power consumption (Mean)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scaph_domain_power_microwatts/1000000",
     "legendFormat": "Socket {{socket_id}} Domain {{domain_name}}"
    },
    {
     "expr": "scaph_socket_power_microwatts/1000000",
     "legendFormat": "Socket {{socket_id}}"
    }
   ]
  },
  {
   "title": "Socket power consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_domain_power_microwatts/1000000",
     "legendFormat": "Socket {{socket_id}} Domain {{domain_name}}"
    },
    {
     "expr": "scaph_socket_power_microwatts/1000000",
     "legendFormat": "Socket {{socket_id}}"
    }
   ]
  },
  {
   "title": "Socket energy consumption",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "scaph_domain_energy_microjoules/3600000000",
     "legendFormat": "Socket {{socket_id}} Domain {{domain_name}}"
    },
    {
     "expr": "scaph_socket_energy_microjoules/3600000000",
     "legendFormat": "Socket {{socket_id}}"
    }
   ]
  },
  {
   "title": "Socket energy consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "scaph_domain_energy_microjoules/1000000/3600",
     "legendFormat": "Socket {{socket_id}} Domain {{domain_name}}"
    },
    {
     "expr": "scaph_socket_energy_microjoules/1000000/3600",
     "legendFormat": "Socket {{socket_id}}"
    }
   ]
  },
  { "title": "Container metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Container energy consumption",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,sum_over_time(sum(scaph_process_power_consumption_microwatts{container_names!=\"\"})by(container_names)[$__range:1s]) / 1000000 / 3600)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container power consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{container_names!=\"\"})by(container_names)/1000000",
     "legendFormat": "{{container_names}}"
    }
   ]
  },
  {
   "title": "Container energy consumption",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum(scaph_process_power_consumption_microwatts{container_names!=\"\"})by(container_names)[$__range:1s]) / 1000000 / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container power consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{container_names!=\"\"})by(container_names)/1000000",
     "legendFormat": "{{container_names}}"
    }
   ]
  },
  {
   "title": "Processes metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Process energy consumption",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8,sum_over_time(sum(scaph_process_power_consumption_microwatts{exe=~\"[^/()]+\"})by(exe)[$__range:1s]) / 1000000 / 3600 > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process power consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{exe=~\"[^/()]+\"})by(exe)/1000000 > 0",
     "legendFormat": "{{exe}}"
    }
   ]
  },
  {
   "title": "Process energy consumption",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum(scaph_process_power_consumption_microwatts{exe=~\"[^/()]+\"})by(exe)[$__range:1s]) / 1000000 / 3600 > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process power consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(scaph_process_power_consumption_microwatts{exe=~\"[^/()]+\"})by(exe)/1000000 > 0",
     "legendFormat": "{{exe}}"
    }
   ]
  }
 ]
}