service:
  interestFeed:
    url: http://localhost:8082

benchmark:
  initialWaitingPeriod: 'PT5S'
  numberOfUsers: 100
  date: '2013-08-05'
  testDuration: 'PT5M'
  requestWaitingPeriod: 'PT1S'

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false