service:
  interestFeed:
    url: http://localhost:8082

benchmark:
  initialWaitingPeriod: 'PT5S'
  numberOfUsers: 100
  date: '2013-08-05'
  testDuration: 'PT5M'
  requestWaitingPeriod: 'PT1S'

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
#  jmx:
#    enabled: true

okhttp:
  client:
    enabled: true
#    protocols: h2_prior_knowledge
#    connect-timeout: 10s
    read-timeout: 30s
#    write-timeout: 10s
    call-timeout: 30s
#    pool:
#      max-idle-connections: 5
#      keep-alive-duration: 5m

server:
  port: 8138
#  http2:
#    enabled: true
  tomcat:
    mbeanregistry:
      # Should be enabled for additional detailed Tomcat metrics
      enabled: true
#    accept-count: 100
    max-connections: 16
#    connection-timeout: 20000
    threads:
      max: 10
      min-spare: 1
  error:
    include-exception: true
    include-stacktrace: never

management:
  server:
    port: 8183
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  #    jmx:
  #      exposure:
  #        include: "*"
  metrics:
    distribution:
      slo:
        http.client.requests:       10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,15s,20s,25s,30s

  #  jmx:
  #    metrics:
  #      export:
  #        enabled: true
  #        step: 4s
  prometheus:
    metrics:
      export:
        enabled: true
        step: 4s

logging:
  level:
    root: INFO

# For metrics configuration see https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics