# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://hub.jupyter.org/helm-chart/
#
proxy:
  service:
    type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - ${jupyterhub_fqdn}

hub:
  config: {}
  # https://tljh.jupyter.org/en/latest/howto/auth/awscognito.html
  extraConfig:
    10_email_domain_as_group.py: |
      def email_domain_as_group(user_data_resp_json):
        email = user_data_resp_json['email']
        domain = email[email.index('@') + 1 : ]
        return [domain]
    20_authenticator.py: |
      from oauthenticator.generic import GenericOAuthenticator
      c.JupyterHub.authenticator_class = GenericOAuthenticator
      c.JupyterHub.admin_access = True
      
      c.GenericOAuthenticator.client_id = "${cognito_app_id}"
      c.GenericOAuthenticator.client_secret = "${cognito_app_secret}"
      c.GenericOAuthenticator.oauth_callback_url = "https://${jupyterhub_fqdn}/hub/oauth_callback"
      
      c.GenericOAuthenticator.authorize_url = "https://${cognito_domain}/oauth2/authorize"
      c.GenericOAuthenticator.token_url = "https://${cognito_domain}/oauth2/token"
      c.GenericOAuthenticator.userdata_url = "https://${cognito_domain}/oauth2/userInfo"
      c.GenericOAuthenticator.logout_redirect_url = "https://${cognito_domain}/oauth2/logout"
      
      c.GenericOAuthenticator.login_service = "AWS Cognito"
      c.GenericOAuthenticator.username_key = "username"
      c.GenericOAuthenticator.userdata_method = "POST"
      
      c.GenericOAuthenticator.allowed_groups = ["${admin_email_domain}", "${user_email_domain}"]
      c.GenericOAuthenticator.admin_groups = ["${admin_email_domain}"]
      c.GenericOAuthenticator.claim_groups_key = email_domain_as_group

singleuser:
  cloudMetadata:
    blockWithIptables: true
    ip: 192.80.8.124
