# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://hub.jupyter.org/helm-chart/
#
proxy:
  service:
    type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - ${jupyterhub_fqdn}

hub:
  config: {}
  # https://tljh.jupyter.org/en/latest/howto/auth/awscognito.html
  # https://jupyterhub.readthedocs.io/en/stable/reference/urls.html
  extraConfig:
    10_email_domain_as_group.py: |
      def email_domain_as_group(user_data_resp_json):
        email = user_data_resp_json['email']
        domain = email[email.index('@') + 1 : ]
        if domain in ${admin_domains}:
          return ["admin"]
        elif domain in ${allowed_domains}:
          return ["user"]
        else:
          return ["anonymous"]
    20_authenticator.py: |
      from oauthenticator.generic import GenericOAuthenticator
      
      c.JupyterHub.authenticator_class = GenericOAuthenticator
      c.JupyterHub.admin_access = True
      
      c.GenericOAuthenticator.client_id = "${cognito_app_id}"
      c.GenericOAuthenticator.client_secret = "${cognito_app_secret}"
      c.GenericOAuthenticator.oauth_callback_url = "https://${jupyterhub_fqdn}/hub/oauth_callback"
      
      c.GenericOAuthenticator.authorize_url = "https://${cognito_domain}/oauth2/authorize"
      c.GenericOAuthenticator.token_url = "https://${cognito_domain}/oauth2/token"
      c.GenericOAuthenticator.userdata_url = "https://${cognito_domain}/oauth2/userInfo"
      c.GenericOAuthenticator.logout_redirect_url = "https://${cognito_domain}/logout?client_id=${cognito_app_id}&logout_uri=${jupyterhub_logout_url_encoded}"
      
      c.GenericOAuthenticator.login_service = "AWS Cognito"
      c.GenericOAuthenticator.username_key = "email"
      c.GenericOAuthenticator.userdata_method = "POST"
      
      c.GenericOAuthenticator.allowed_groups = ["user"%{ if allow_all_domains },"anonymous"%{ endif }]
      c.GenericOAuthenticator.admin_groups = ["admin"]
      c.GenericOAuthenticator.claim_groups_key = email_domain_as_group

singleuser:
  image:
    name: enviteconsulting/jupyterlab-gswe-ki-ml-exercise
    tag: 0.1.0

  # https://z2jh.jupyter.org/en/latest/jupyterhub/customizing/user-environment.html#using-nbgitpuller-to-synchronize-a-folder
  lifecycleHooks:
    postStart:
      exec:
        command:
          [
            "tini",
            "--",
            "/usr/local/bin/_entrypoint.sh",
            "gitpuller",
            "https://gitlab.com/envite-consulting/gswe-lecture-public/ki-ml-exercise.git",
            "main",
            "ki-ml-exercise",
          ]

  storage:
    extraVolumeMounts:
      - mountPath: /proc/cpuinfo
        name: cpuinfo
        readOnly: true
      - mountPath: /sys
        name: sys
        readOnly: true
    extraVolumes:
      - hostPath:
          path: /proc/cpuinfo
          type: "File"
        name: cpuinfo
      - hostPath:
          path: /sys
          type: "Directory"
        name: sys

  cloudMetadata:
    blockWithIptables: true
    ip: 192.80.8.124

  cpu:
    limit: 4
    guarantee: 1
  memory:
    limit: 4G
    guarantee: 2G

# https://github.com/jupyterhub/jupyterhub-idle-culler#as-a-standalone-script
cull:
  enabled: true
  users: false # --cull-users
  adminUsers: false # --cull-admin-users
  removeNamedServers: false # --remove-named-servers
  timeout: 3600 # --timeout
  every: 3600 # --cull-every
  concurrency: 1 # --concurrency
  maxAge: 0 # --max-age