global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'news'
    static_configs:
      - targets: ['news:8181']
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [job]
        action: replace
        target_label: service
  - job_name: 'interest-feed'
    static_configs:
      - targets: ['interest-feed:8182']
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [job]
        action: replace
        target_label: service

  - job_name: 'redis'
    static_configs:
      - targets:
          - redis://user-interest-db:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-prometheus-exporter:9121
      - source_labels: [__param_target]
        regex: redis://(.*):.*
        replacement: $1
        target_label: service

  - job_name: 'mariadb'
    static_configs:
      - targets:
          - news-db:3306
    metrics_path: /probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mariadb-prometheus-exporter:9104
      - source_labels: [__param_target]
        regex: (.*):.*
        replacement: $1
        target_label: service

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"