server:
  port: 8082
  shutdown: graceful
  tomcat:
    mbeanregistry:
      # Should be enabled for additional detailed Tomcat metrics
      enabled: true
#    accept-count: 100 #100
    max-connections: 15000 #8192
    connection-timeout: 60000 #20000
    threads:
      max: 400 #200
#      min-spare: 10 #10
  error:
    include-exception: true
    include-stacktrace: never

spring:
  data:
    redis:
      host: localhost
      port: 6379
  jmx:
    enabled: true

service:
  news:
    url: http://localhost:8081

feed:
  limit: 20
  period: 1m

management:
  server:
    port: 8182
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      slo:
        http.server.requests: 10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,15s,20s,25s,30s
        http.client.requests: 10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,15s,20s,25s,30s

logging:
  level:
    root: INFO
