feed:
  limit: 20
  period: 1m

service:
  news:
    url: http://localhost:8081

spring:
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    serialization:
      write-dates-as-timestamps: false
#  jmx:
#    enabled: true

#thread:
#  virtual: true

server:
  port: 8082
  shutdown: graceful
#  http2:
#    enabled: true
  tomcat:
    mbeanregistry:
      # Should be enabled for additional detailed Tomcat metrics
      enabled: true
#    accept-count: 100
#    max-connections: 8192
#    connection-timeout: 20000
#    threads:
#      max: 200
#      min-spare: 10
  error:
    include-exception: true
    include-stacktrace: never

okhttp:
  client:
    enabled: false
#    protocols: h2_prior_knowledge
#    connect-timeout: 10s
#    read-timeout: 10s
#    write-timeout: 10s
#    call-timeout: 0s
#    pool:
#      max-idle-connections: 5
#      keep-alive-duration: 5m

management:
  server:
    port: 8182
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
#    jmx:
#      exposure:
#        include: "*"
  metrics:
    distribution:
      slo:
        http.server.requests: 10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,15s,20s,25s,30s
        http.client.requests: 10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,15s,20s,25s,30s
        method.timed:         10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,15s,20s,25s,30s
#  jmx:
#    metrics:
#      export:
#        enabled: true
#        step: 4s
  prometheus:
    metrics:
      export:
        enabled: true
        step: 4s

logging:
  level:
    root: INFO

# For metrics configuration see https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics