feed:
  limit: 20
  period: P1W
  use-recommended-news: true
  use-latest-news: true

service:
  news:
    url: http://localhost:8081

spring:
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    serialization:
      write-dates-as-timestamps: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
#  jmx:
#    enabled: true

#web-resource:
#  feed:
#    cache-control:
#      enabled: true
#      by-user: 1m
#  interests:
#    cache-control:
#      enabled: true
#      all: 1m
#      by-user: 1m
#  usernames:
#    cache-control:
#      enabled: true
#      all: 1m

server:
  port: 8082
  shutdown: graceful
#  http2:
#    enabled: true
  tomcat:
    mbeanregistry:
      # Should be enabled for additional detailed Tomcat metrics
      enabled: true
#    accept-count: 100
#    max-connections: 8192
#    connection-timeout: 20000
#    threads:
#      executor: virtual # platform
#      max: 200
#      min-spare: 10
  error:
    include-exception: true
    include-stacktrace: never

#okhttp:
#  client:
#    enabled: false
#    protocols: h2_prior_knowledge
#    connect-timeout: 10s
#    read-timeout: 10s
#    write-timeout: 10s
#    call-timeout: 0s
#    pool:
#      max-idle-connections: 5
#      keep-alive-duration: 5m
#    cache:
#      enabled: false
#      directory: "/home/cnb/.cache/http_cache"
#      max-size: 10MB

management:
  server:
    port: 8182
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
#    jmx:
#      exposure:
#        include: "*"
  metrics:
    distribution:
      slo:
        http.server.requests:       10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,15s,20s,25s,30s
        http.client.requests:       10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,15s,20s,25s,30s
        method.timed:               10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,15s,20s,25s,30s
        lettuce.command:            50us,100us,250us,500us,1ms,2ms,5ms,10ms,50ms,100ms,250ms,750ms,1s,5s
        feed.recommended.news.size: 0.1,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0

#  jmx:
#    metrics:
#      export:
#        enabled: true
#        step: 4s
  prometheus:
    metrics:
      export:
        enabled: true
        step: 4s

logging:
  level:
    root: INFO

# For metrics configuration see https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics