project             = "playground-26597"
region              = "europe-north1"
environment         = "talk"
ip_cidr_range       = "10.0.2.0/24"
machine_type        = "e2-highcpu-16"
image_ubuntu_family = "ubuntu-2304-amd64"
image_size_gb       = "50"