spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/newsdb
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 10
#      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
  lifecycle:
    timeout-per-shutdown-phase: 30s
#  jmx:
#    enabled: true

#web-resource:
#  news:
#    cache-control:
#      enabled: true
#      recommended-news: 1m
#      latest-news: 1m

server:
  port: 8081
  shutdown: graceful
  #  http2:
  #    enabled: true
  tomcat:
    mbeanregistry:
      # Should be enabled for additional detailed Tomcat metrics
      enabled: true
  #    accept-count: 100
  #    max-connections: 8192
  #    connection-timeout: 20000
  #    threads:
  #      executor: virtual # platform
  #      max: 200
  #      min-spare: 10
  error:
    include-exception: true
    include-stacktrace: never

management:
  server:
    port: 8181
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  #    jmx:
  #      exposure:
  #        include: "*"
  metrics:
    distribution:
      slo:
        http.server.requests: 10ms,25ms,50ms,100ms,200ms,300ms,400ms,500ms,600ms,700ms,800ms,900ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,11s,12s,13s,14s,15s,16s,17s,18s,19s,20s,25s
        method.timed:         10ms,25ms,50ms,100ms,200ms,300ms,400ms,500ms,600ms,700ms,800ms,900ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,11s,12s,13s,14s,15s,16s,17s,18s,19s,20s,25s
        hikaricp.connections: 10ms,25ms,50ms,100ms,200ms,300ms,400ms,500ms,600ms,700ms,800ms,900ms,1s,2s,3s,4s,5s,6s,7s,8s,9s,10s,11s,12s,13s,14s,15s,16s,17s,18s,19s,20s,25s
    data:
      repository:
        autotime:
          enabled: false
  #  jmx:
  #    metrics:
  #      export:
  #        enabled: true
  #        step: 4s
  prometheus:
    metrics:
      export:
        enabled: true
        step: 4s

logging:
  level:
    root: INFO

# For metrics configuration see https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics