server:
  port: 8081
  shutdown: graceful

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/newsdb
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate